### ISSUE TITLE
Future of package?

### ISSUE THREAD

**Issue by garrison** [timholy/DebuggingUtilities.jl#9]
Any plans to register this package?

To be honest, I find `@showln` so useful that I wish it were in Base.  (In other words, I wish I didn't have to temporarily write `using DebuggingUtilities` at the top of my package in order to use it.)

I know, I know, you've put all this fabulous work into there being a *real* Julia debugger, and I just want to use `@showln`. :slightly_smiling_face:

**Comment by timholy** [comment]
I could register it, as it is indeed quite useful sometimes. I think I use it less because it's not registered, and hence when you're inside a `--project` it doesn't know about it.

Care to comment on any aspect of its design? Anything you particularly like or dislike? I seem to remember that the indenting is one of the things I wrestled with.

**Comment by timholy** [comment]
There might also be a way to implement it now without taking a full backtrace. Might merit investigation.

**Comment by garrison** [comment]
Thanks for the reply!

> Care to comment on any aspect of its design? Anything you particularly like or dislike?

I haven't looked much at the design; I just know that I have found `@showln` very useful.
